version: '3.9'
services:
  user-database:
    container_name: user-database
    image: postgres:alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rahasia
      - POSTGRES_DB=user-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-server
  user-service:
    container_name: user-service
    build: .
    networks:
      - api-server
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:rahasia@user-database:5432/user-service?schema=public
      - SECRET_KEY=rahasia
    depends_on:
      - user-database
networks:
  api-server:
    external: true
volumes:
  pgdata: {}